### ISSUE TITLE
Error: Could not find or load main class io.ray.runtime.runner.worker.DefaultWorker

### ISSUE THREAD

**Issue by james-tn** [oap-project/raydp#208]
Hello,
I setup a ray cluster, install java on the node but when I do spark_init, the above error occurred in workers's node. 
I checked ray dashboard, the actors for worker nodes are in pending status. Only the actor for head node could be created.

**Comment by kira-lin** [comment]
Hi,
Thanks for trying raydp. Your issue is quite similar to #199 . The error says it cannot find ray's java main class to start java workers. There should be some error with the environment. Can you find ray's jar under the same path on all nodes?

**Comment by james-tn** [comment]
For each worker, the path to ray's jars is like this: /ML_ENV/NODE_ID/lib/python3.8/site-packages/ray/jars/ray_dist.jar where NODE_ID is unique to each worker.
The cluster is setup manually where head node starts first then each worker follows. I have no problem with other ray packages but only spark on ray.

**Comment by james-tn** [comment]
I saw the issue 199 and I think the problem is that in my driver environment the paths to raydp and ray jars are different from that of workers. I made the jars available at workers in the same path as the driver so the above error no longer appeared. Actors were started but those at workers all died. The log at those dead actors is like this:
12022-01-29 02:57:15,399 ERROR TaskExecutor [main]: Failed to execute task ffffffffffffffff47a5690c98571e67d5c3327a02000000 . rayFunction is null , argument types are null2java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging.
 
Any idea why? JAVA_HOME was not set.

**Comment by carsonwang** [comment]
Java is required on every worker node and JAVA_HOME needs to be set. Please also check the version. RayDP 0.4.1 should work with Ray 1.8/1.9 and pySpark 3.2.0. Did you install pySpark through pip? If you have SPARK_HOME set to another install, please  unset it. Another thing to try is to run pySpark on your worker node to make sure the Java environment and pySpark itself can work properly first.

**Comment by james-tn** [comment]
I used RayDP nightly. Pyspark was installed via pip. I checked Java is there in worker node. RayDP can run, it’s just that the actors only survived in head node. The error came from io.ray. I’ll test pyspark in worker node.

**Comment by james-tn** [comment]
It turned out that the RayDP also expects the pyspark in workers to the in the same directory as in the driver node. I needed to create the same Raydp, ray and pyspark jars in the workers for this to work. I think the raydp.executor.extraClassPath should support adding multiple paths instead of just one like.
